"""
Django settings for finargo project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from decouple import config as env_conf
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_conf('DJANGO_KEY')

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    # UNFOLD
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'parler',
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # My apps
    'invest.apps.InvestConfig',
    'portfolio.apps.PortfolioConfig',
    'notes.apps.NotesConfig',
    'statements.apps.StatementsConfig',
    'news.apps.NewsConfig',
    'analysis.apps.AnalysisConfig',
    'site_admin.apps.AdminConfig',
    'user_profile.apps.UserProfileConfig',
    # External apps
    'channels',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'corsheaders',
    'django_celery_beat',
    'django_celery_results',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'i18n.middleware.DynamicLanguageMiddleware',
    # 'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Celery
CELERY_BROKER_URL = env_conf('CELERY_BROKER_URL')
CELERY_TASK_TRACK_STARTED = True  # запускает трекинг задач Celery

# Планировщик задач
CELERY_BEAT_SCHEDULER = \
    'django_celery_beat.schedulers:DatabaseScheduler'  # Celery настроен на использование планировщика из базы данных

CELERY_BROKER_TRANSPORT_OPTION = {'visibility_timeout': 3600}  # время ожидания видимости 1 час
CELERY_RESULT_BACKEND = 'django-db'  # указание для django_celery_results куда записывать результат выполнения задач
CELERY_ACCEPT_CONTENT = ['application/json']  # это тип содержимого, разрешенный к получению
CELERY_TASK_SERIALIZER = 'json'  # это строка, используемая для определения метода сериализации по умолчанию
CELERY_RESULT_SERIALIZER = 'json'  # является типом формата сериализации результатов

CELERY_TASK_DEFAULT_QUEUE = 'default'  # celery будет использовать это имя очереди
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Django CORS Headers
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Русский'),
    ('fr', 'Français'),
    ('es', 'Español'),
    ('de', 'Deutsch'),
    ('pl', 'Polski'),
    ('it', 'Italiano'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

PARLER_DEFAULT_LANGUAGE_CODE = 'en'

PARLER_LANGUAGES = {
    None: (
        {'code': 'en', },
        {'code': 'ru', },
        {'code': 'fr', },
        {'code': 'es', },
        {'code': 'de', },
        {'code': 'pl', },
        {'code': 'it', },
    ),
    'default': {
        'fallbacks': ['en'],  # defaults to PARLER_DEFAULT_LANGUAGE_CODE
        'hide_untranslated': False,  # the default; let .active_translations() return fallbacks too.
    }
}

# UNFOLD
UNFOLD = {
    "SHOW_HISTORY": True, # show/hide "History" button, default: True
    "SHOW_VIEW_ON_SITE": True, # show/hide "View on site" button, default: True
    "SHOW_BACK_BUTTON": False, # show/hide "Back" button on changeform in header, default: False
    "BORDER_RADIUS": "8px",
    "COLORS": {
        "base": {
            "50": "249, 250, 251",
            "100": "243, 244, 246",
            "200": "229, 231, 235",
            "300": "209, 213, 219",
            "400": "156, 163, 175",
            "500": "107, 114, 128",
            "600": "75, 85, 99",
            "700": "55, 65, 81",
            "800": "31, 41, 55",
            "900": "17, 24, 39",
            "950": "3, 7, 18",
        },
        "primary": {
            "50": "250, 245, 255",
            "100": "243, 232, 255",
            "200": "233, 213, 255",
            "300": "216, 180, 254",
            "400": "192, 132, 252",
            "500": "33, 145, 235",
            "600": "33, 145, 235",
            "700": "126, 34, 206",
            "800": "107, 33, 168",
            "900": "88, 28, 135",
            "950": "59, 7, 100",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",  # text-base-500
            "subtle-dark": "var(--color-base-400)",  # text-base-400
            "default-light": "var(--color-base-600)",  # text-base-600
            "default-dark": "var(--color-base-300)",  # text-base-300
            "important-light": "var(--color-base-900)",  # text-base-900
            "important-dark": "var(--color-base-100)",  # text-base-100
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": True,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _('Analysis'),
                "collapsible": True,
                "items": [
                    {
                        "title": _('Analysis'),
                        "icon": 'network_intelligence',
                        'link': reverse_lazy(
                            "admin:analysis_companyanalysis_changelist",
                        ),
                    }
                ],
            },
            {
                "title": _('Celery results'),
                "collapsible": True,
                "items": [
                    {
                        "title": _('Group Results'),
                        "icon": 'sports_score',
                        'link': reverse_lazy(
                            "admin:django_celery_results_groupresult_changelist",
                        ),
                    },
                    {
                        "title": _('Task results'),
                        "icon": 'sports_score',
                        'link': reverse_lazy(
                            "admin:django_celery_results_taskresult_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _('Invest'),
                "collapsible": True,
                "items": [
                    {
                        "title": _('Analyst ideas'),
                        "icon": 'online_prediction',
                        "link": reverse_lazy(
                            "admin:invest_analystidea_changelist"
                        ),
                    },
                    {
                        "title": _('Analysts'),
                        "icon": 'groups_3',
                        "link": reverse_lazy(
                            "admin:invest_analyst_changelist"
                        ),
                    },
                    {
                        "title": _('Candles per day'),
                        "icon": 'candlestick_chart',
                        "link": reverse_lazy(
                            "admin:invest_candleperday_changelist"
                        ),
                    },
                    {
                        "title": _('Companies'),
                        "icon": 'apartment',
                        "link": reverse_lazy(
                            "admin:invest_company_changelist"
                        ),
                    },
                    {
                        "title": _('Countries'),
                        "icon": 'public',
                        "link": reverse_lazy(
                            "admin:invest_country_changelist"
                        ),
                    },
                    {
                        "title": _('Currencies'),
                        "icon": 'euro_symbol',
                        "link": reverse_lazy(
                            "admin:invest_currency_changelist"
                        ),
                    },
                    {
                        "title": _('Dividends'),
                        "icon": 'confirmation_number',
                        "link": reverse_lazy(
                            "admin:invest_dividend_changelist"
                        ),
                    },
                    {
                        "title": _('Industries'),
                        "icon": 'precision_manufacturing',
                        "link": reverse_lazy(
                            "admin:invest_industry_changelist"
                        ),
                    },
                    {
                        "title": _('Markets'),
                        "icon": 'api',
                        "link": reverse_lazy(
                            "admin:invest_market_changelist"
                        ),
                    },
                    {
                        "title": _('Reports metadata'),
                        "icon": 'browse_activity',
                        "link": reverse_lazy(
                            "admin:invest_reportmetadata_changelist"
                        ),
                    },
                    {
                        "title": _('Sectors'),
                        "icon": 'factory',
                        "link": reverse_lazy(
                            "admin:invest_sector_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _('News'),
                "collapsible": True,
                "items": [
                    {
                        "title": _('News'),
                        "icon": 'newspaper',
                        'link': reverse_lazy(
                            "admin:news_news_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _('Notes'),
                "collapsible": True,
                "items": [
                    {
                        "title": _('Notes'),
                        "icon": 'draw',
                        "link": reverse_lazy(
                            "admin:notes_note_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _('Portfolio'),
                "collapsible": True,
                "items": [
                    {
                        "title": _('Portfolio Companies'),
                        "icon": 'work_update',
                        "link": reverse_lazy(
                            "admin:portfolio_portfoliocompany_changelist"
                        ),
                    },
                    {
                        "title": _('Portfolio'),
                        "icon": 'enterprise',
                        "link": reverse_lazy(
                            "admin:portfolio_portfolio_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _('Statements'),
                "collapsible": True,
                "items": [
                    {
                        "title": _('Statements'),
                        "icon": 'search_check_2',
                        'link': reverse_lazy(
                            "admin:statements_statement_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _('User Profiles'),
                "collapsible": True,
                "items": [
                    {
                        "title": _('Profiles'),
                        "icon": 'badge',
                        "link": reverse_lazy(
                            "admin:user_profile_profile_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Celery Tasks"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Clocked"),
                        "icon": "hourglass_bottom",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_clockedschedule_changelist"
                        ),
                    },
                    {
                        "title": _("Crontabs"),
                        "icon": "update",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_crontabschedule_changelist"
                        ),
                    },
                    {
                        "title": _("Intervals"),
                        "icon": "timer",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_intervalschedule_changelist"
                        ),
                    },
                    {
                        "title": _("Periodic tasks"),
                        "icon": "task",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_periodictask_changelist"
                        ),
                    },
                    {
                        "title": _("Solar events"),
                        "icon": "event",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_solarschedule_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _('Users & Groups'),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _('Auth Tokens'),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Token"),
                        "icon": 'password',
                        "link": reverse_lazy("admin:authtoken_tokenproxy_changelist"),
                    },
                ],
            },
        ],
    },
}

