from invest.models import Company
from statements.checks.initials import (
    AreRevenueAndEarningsExpectedToGrowCheck,
    HasBeenGrowingProfitOrRevenueCheck,
    HasCapitalisationRateIncreasedSignificantlyCheck,
    HasCashFromOperationGrownSlowerThanNetIncomeCheck,
    HasDecliningGrossProfitMarginsCheck,
    HasDecliningProfitMarginsCheck,
    HasFiledWithinMonthsCheck,
    HasFiledWithinPastYearCheck,
    HasFinancialDataCheck,
    HasHighAccrualsRatioCheck,
    HasHighQualityEarningsCheck,
    HasInventoryGrownSignificantlyFasterThanSalesCheck,
    HasLargeDecreaseInUnearnedRevenueCheck,
    HasLargeIncreaseInAccountsReceivableCheck,
    HasLargeNegativeOneTimeChargesCheck,
    HasLargeOneTimeChargesCheck,
    HasLargePositiveOneTimeChargesCheck,
    HasLargePositiveOneTimeChargesAndProfitableCheck,
    HasMeaningfulMarketCapCheck,
    HasMeaningfulRevenueCheck,
    HasNegativeGrossMarginCheck,
    HasNetProfitMarginImprovedOverPastYearCheck,
    HasNoConcerningRecentEventsCheck,
    HasNoNegativeEquityCheck,
    HasNoSubstantialInsiderSellingOverPastQuarterCheck,
    HasNotDilutedOverPastYearCheck,
    HasSignificantNonOperatingRevenueCheck,
    HasStableSharePriceCheck,
    HasStableSharePriceOverPast3MonthsCheck,
    HasSufficientFinancialDataCheck,
    IsAbleToAchieveProfitabilityCheck,
    IsDividendAttractiveCheck,
    IsDividendSustainableCheck,
    IsGoodRelativeValueCheck,
    IsGoodValueCheck,
    IsGoodValueComparedToIndustryCheck,
    IsGoodValueComparedToPeersCheck,
    IsGrowingProfitOrRevenueCheck,
    IsInAGoodFinancialPositionCheck,
    IsProfitableOnAverageOrCurrentCheck,
    IsTradingBelowAnalystPriceTargetsCheck,
    IsTradingBelowFairRatioCheck,
)
from statements.types import Fields
from statements.checks.value import (
    BelowFairValueCheck,
    SignificantlyBelowFairValueCheck,
    PriceToEarningsVsPeersCheck,
    PriceToEarningsVsIndustryCheck,
    PriceToEarningsVsFairRatioCheck,
    AnalystForecastCheck,
    ReturnVsMarketCheck,
    ReturnVsIndustryCheck,
)
from statements.checks.future import (
    EarningsVsSavingRateCheck,
    EarningsVsMarketCheck,
    HighGrowthEarningsCheck,
    RevenueVsMarketCheck,
    HighGrowthRevenueCheck,
    FutureROECheck,
)
from statements.checks.past import (
    QualityEarningsCheck,
    GrowingProfitMarginCheck,
    EarningsTrendCheck,
    AcceleratingGrowthCheck,
    EarningsVsIndustryCheck,
    HighROECheck,
    StableSharePriceCheck,
    VolatilityOverTimeCheck,
)
from statements.checks.health import (
    ShortTermLiabilitiesCheck,
    LongTermLiabilitiesCheck,
    DebtLevelCheck,
    ReducingDebtCheck,
    DebtCoverageCheck,
    InterestCoverageCheck,
)
from statements.checks.dividend import (
    SignificantDividendCheck,
    HighDividendCheck,
    StableDividendCheck,
    GrowingDividendCheck,
    EarningsCoverageCheck,
    CashFlowCoverageCheck,
)


def main(companies: list[Company] = None):
    if not companies:
        companies = Company.objects.filter(is_visible=True)

    objects = []

    for company in companies:
        fields = get_fields(company)

        objects.append([
            # INIT
            AreRevenueAndEarningsExpectedToGrowCheck(fields),
            HasBeenGrowingProfitOrRevenueCheck(fields),
            HasCapitalisationRateIncreasedSignificantlyCheck(fields),
            HasCashFromOperationGrownSlowerThanNetIncomeCheck(fields),
            HasDecliningGrossProfitMarginsCheck(fields),
            HasDecliningProfitMarginsCheck(fields),
            HasFiledWithinMonthsCheck(fields),
            HasFiledWithinPastYearCheck(fields),
            HasFinancialDataCheck(fields),
            HasHighAccrualsRatioCheck(fields),
            HasHighQualityEarningsCheck(fields),
            HasInventoryGrownSignificantlyFasterThanSalesCheck(fields),
            HasLargeDecreaseInUnearnedRevenueCheck(fields),
            HasLargeIncreaseInAccountsReceivableCheck(fields),
            HasLargeNegativeOneTimeChargesCheck(fields),
            HasLargeOneTimeChargesCheck(fields),
            HasLargePositiveOneTimeChargesCheck(fields),
            HasLargePositiveOneTimeChargesAndProfitableCheck(fields),
            HasMeaningfulMarketCapCheck(fields),
            HasMeaningfulRevenueCheck(fields),
            HasNegativeGrossMarginCheck(fields),
            HasNetProfitMarginImprovedOverPastYearCheck(fields),
            HasNoConcerningRecentEventsCheck(fields),
            HasNoNegativeEquityCheck(fields),
            HasNoSubstantialInsiderSellingOverPastQuarterCheck(fields),
            HasNotDilutedOverPastYearCheck(fields),
            HasSignificantNonOperatingRevenueCheck(fields),
            HasStableSharePriceCheck(fields),
            HasStableSharePriceOverPast3MonthsCheck(fields),
            HasSufficientFinancialDataCheck(fields),
            IsAbleToAchieveProfitabilityCheck(fields),
            IsDividendAttractiveCheck(fields),
            IsDividendSustainableCheck(fields),
            IsGoodRelativeValueCheck(fields),
            IsGoodValueCheck(fields),
            IsGoodValueComparedToIndustryCheck(fields),
            IsGoodValueComparedToPeersCheck(fields),
            IsGrowingProfitOrRevenueCheck(fields),
            IsInAGoodFinancialPositionCheck(fields),
            IsProfitableOnAverageOrCurrentCheck(fields),
            IsTradingBelowAnalystPriceTargetsCheck(fields),
            IsTradingBelowFairRatioCheck(fields),
            # VALUE
            BelowFairValueCheck(fields),
            SignificantlyBelowFairValueCheck(fields),
            PriceToEarningsVsPeersCheck(fields),
            PriceToEarningsVsIndustryCheck(fields),
            PriceToEarningsVsFairRatioCheck(fields),
            AnalystForecastCheck(fields),
            ReturnVsMarketCheck(fields),
            ReturnVsIndustryCheck(fields),
            # FUTURE
            EarningsVsSavingRateCheck(fields),
            EarningsVsMarketCheck(fields),
            HighGrowthEarningsCheck(fields),
            RevenueVsMarketCheck(fields),
            HighGrowthRevenueCheck(fields),
            FutureROECheck(fields),
            # PAST
            QualityEarningsCheck(fields),
            GrowingProfitMarginCheck(fields),
            EarningsTrendCheck(fields),
            AcceleratingGrowthCheck(fields),
            EarningsVsIndustryCheck(fields),
            HighROECheck(fields),
            StableSharePriceCheck(fields),
            VolatilityOverTimeCheck(fields),
            # HEALTH
            ShortTermLiabilitiesCheck(fields),
            LongTermLiabilitiesCheck(fields),
            DebtLevelCheck(fields),
            ReducingDebtCheck(fields),
            DebtCoverageCheck(fields),
            InterestCoverageCheck(fields),
            # DIVIDEND
            SignificantDividendCheck(fields),
            HighDividendCheck(fields),
            StableDividendCheck(fields),
            GrowingDividendCheck(fields),
            EarningsCoverageCheck(fields),
            CashFlowCoverageCheck(fields),
        ])

    return objects


def get_fields(company_object):
    return Fields(
        # Common
        company_object=company_object,
        slug=company_object.slug,
        currency='₽',
        market_country_adjectif='russian',
        sector_company_name='banks',
        # Value
        company_current_price=company_object.candles.order_by('-time')[0].close,
        average_price_target_1y=400,
        company_fair_price=329.48,
        company_pe=5.0,
        peers_pe=4.8,
        industry_pe=4.8,
        company_fair_pe=4.8,
        return_1y=0.33,
        market_return_1y=0.282,
        sector_market_return_1y=0.299,
        # Future
        company_forecast_earnings_growth=0.082,
        country_saving_rate=0.075,
        market_forecast_earnings_growth=0.092,
        company_forecast_revenue_growth=0.0125,
        market_forecast_revenue_growth=0.033,
        company_future_roe_3y=0.0199,
        # Past
        company_earnings=1_158_600_000_000,
        company_profit_margins=0.476,
        past_profit_margins=0.419,
        company_earnings_growth_5y=0.101,
        company_earnings_growth=0.524,
        industry_earnings_growth=0.146,
        company_roe=0.209,
        volatility_3m=0.017,
        volatility_1y=0.29,
        volatility_1y_past_year=0.17,
        sector_market_volatility_3m=0.032,
        # Health
        company_short_term_assets=6_271_400_000_000,
        company_short_term_liabilities=31_154_700_000_000,
        company_long_term_liabilities=4_366_300_000_000,
        company_net_debt_to_equity_ratio=0.027,
        company_debt=9_700_000_000,
        company_debt_to_equity_ratio=0.903,
        company_debt_to_equity_ratio_5Y_ago=0.99,
        company_operating_cash_flow=-100_000_000,
        company_interest_rate=0.09,
        company_ebit=100_000_000,
        # Dividend
        company_dividend_yield=0.1403,
        market_dividend_yield_p25=0.0443,
        market_dividend_yield_p75=0.1315,
        company_dividend_is_volatile_in_10y=True,
        company_dividend_amount=539_673_700_000,
        company_dividend_amount_10y_ago=55_678_456_360,
        company_payout_ratio=0.347,
        company_cash_payout_ratio=0,
        # Risks
        earnings_growth_per_year_forecast_3y=0.082,
        capitalisation_rate=0.07,
        capitalisation_rate_1y=0.05,
        operating_cash_flow_growth=0.6,
        gross_profit_margin=0.97,
        gross_profit_margin_1y=0.98,
        sloan_ratio=0.15,  # =(Net Income-CFO(Cash Flow from Operations)-CFI(Cash Flow from Investments))/Total Assets
        inventory_growth=0.20,
        sales_growth=0.25,
        unearned_revenue_growth=0.25,
        accounts_receivable_growth=0.25,
        one_off_charges=5_000_000,
        market_cap_usd=42_000_000_000,
        market_cap=4_000_000_000_000,
        revenue=3_000_000_000_000,
        events_was_occurred=True,
        substantial_insider_selling_was_occurred=True,
        has_diluted_over_past_year=True,
        non_operating_revenue=100_000_000,
        operating_revenue=1_500_000_000_000,
        cash_and_cash_equivalents=100_000_000,
        cash_expenses=50_000_000,
        equity=5_000_000_000,
    )
